// <auto-generated />
namespace versity.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_description_to_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_description_to_item));
        
        string IMigrationMetadata.Id
        {
            get { return "201409051734321_add_description_to_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
