// <auto-generated />
namespace versity.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class remove_categories_add_items : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_categories_add_items));
        
        string IMigrationMetadata.Id
        {
            get { return "201408212202577_remove_categories_add_items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
