// <auto-generated />
namespace versity.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_menus_to_restaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_menus_to_restaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "201408181950157_add_menus_to_restaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
